language: R
sudo: required #false
dist: focal
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- mkdir ~/.R
#- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  skip_cleanup: true
