# Licencia {#licence}

Licencia Reconocimiento-NoComercial-SinObraDerivada 3.0 España (CC BY-NC-ND 3.0 ES ; https://creativecommons.org/licenses/by-nc-nd/3.0/es/)
    
Esto es un resumen inteligible para humanos (y no un sustituto) de la licencia.

**Usted es libre de:**

* Compartir — copiar y redistribuir el material en cualquier medio o formato.
* El licenciador no puede revocar estas libertades mientras cumpla con los términos de la licencia.

**Bajo las condiciones siguientes:**

* Reconocimiento — Debe reconocer adecuadamente la autoría, proporcionar un enlace a la licencia e indicar si se han realizado cambios<. Puede hacerlo de cualquier manera razonable, pero no de una manera que sugiera que tiene el apoyo del licenciador o lo recibe por el uso que hace.  

* NoComercial — No puede utilizar el material para una finalidad comercial. 

* SinObraDerivada — Si remezcla, transforma o crea a partir del material, no puede difundir el material modificado.  

* No hay restricciones adicionales — No puede aplicar términos legales o medidas tecnológicas que legalmente restrinjan realizar aquello que la licencia permite.  

**Avisos: **

No tiene que cumplir con la licencia para aquellos elementos del material en el dominio público o cuando su utilización esté permitida por la aplicación de una excepción o un límite.
No se dan garantías. La licencia puede no ofrecer todos los permisos necesarios para la utilización prevista. Por ejemplo, otros derechos como los de publicidad, privacidad, o los derechos morales pueden limitar el uso del material.
