---
title: "Aprender R: iniciación y perfeccionamiento"
author: "François Rebaudo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib]
biblio-style: apalike
#link-citations: yes
#github-repo: https://github.com/frareb/myRBook_FR
#url: 'http://myrbookfr.netlify.com/'
description: "Un guía para adquirir las bases de la programación con R y conducir de forma efectiva su gestión y análisis de datos."
---

# Preámbulo

Este libro está incompleto por el momento y está leyendo su versión preliminar. Si tiene algún comentario, sugerencia o si identifica errores, no dude en enviarme un correo electrónico (francois.rebaudo@ird.fr), o si está familiarizado con GitHub en el sitio web del proyecto (https://github.com/frareb/myRBook_SP).

Últimas modificaciones:

**27/07/2018**

* Capítulo sobre las funciones (2/3)

**25/07/2018**

* Capítulo sobre las funciones (1/3)

**17/07/2018**

* edición y corrección del español (Susi L.) 
* tercera parte del capítulo *Contenedores de datos*: El contenedor *data.frame*
* cuarta parte del capítulo *Contenedores de datos*: El contenedor *matrix*
* quinta parte del capítulo *Contenedores de datos*: El contenedor *array*

**16/07/2018**

* edición y corrección del español (Estefanía Q.) 

**12/07/2018**

* segunda parte del capítulo *Contenedores de datos*: El contenedor *list*

**06/07/2018**

* edición y corrección del español (Camila B.) 
* primera parte del capítulo *Contenedores de datos*: El contenedor *vector*

**04/07/2018**

* tabla de contenidos con los próximos capítulos
* error de tipografía en *Elegir un entorno de desarrollo*

**02/07/2018**

* tres capítulos en línea (*primeros pasos*, *elegir un entorno de desarrollo*, *tipos de datos*)


# Agradecimientos {#remerciements}

Agradezco a todos los colaboradores que ayudaron a mejorar este libro con sus consejos, sugerencias de cambios y correcciones (en orden alfabético):

```{r echo = FALSE}
contrib <- unname(t(data.frame(
  c("Camila", "Benavides Frias", "Bolivia"), 
  c("Estefania", "Quenta Herrera",  "Bolivia"), 
  c("Susi", "Loza Herrera", "Bolivia")
)))
contrib <- contrib[order(contrib[, 2]),]
msg <- "Colaboradores :\r"
for(i in seq_along(contrib[, 2])){
  msg <- c(msg, paste0(contrib[i, 1], " ",contrib[i, 2], " (", contrib[i, 3],")\r"))
}
for(i in msg){cat(i, sep = "")}
```

Las versiones de gitbook, html y epub de este libro usan los iconos de fuente abierta de Font Awesome (https://fontawesome.com). La versión en PDF utiliza los iconos del proyecto Tango disponibles en openclipart (https://openclipart.org/). Este libro fue escrito con el paquete R bookdown (https://bookdown.org/). El código fuente está disponible en GitHub (https://github.com/frareb/myRBook_SP). La compilación usa Travis CI (https://travis-ci.org). La versión en línea se aloja y actualiza a través de Netlify (http://myrbooksp.netlify.com/).
